{% set name = "knitty" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 533b6466ca78f8a688b9e22499bab09bd887fe91e16e723ac587d8d6f09c63f0

build:
  noarch: python
  number: 0
  entry_points:
    - knitty = knitty.knitty:main
    - pre-knitty = knitty.pre_knitty:main
    - pandoc-filter-arg = knitty.pandoc_filter_arg.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - panflute >=1.11.2
    - jupyter_core
    - traitlets
    - ipython
    - jupyter_client
    - nbconvert >=5.4.1
    - pandocfilters
    #- py-pandoc >=2.6
    - click
    - psutil
    - pyyaml
    - shutilwhich-cwdpatch >=0.1.0
    - ipykernel

test:
  imports:
    - knitty
    - knitty.api
    - knitty.tools
    - knitty.stitch
    - knitty.pandoc_filter_arg
  commands:
    - knitty --help
    - pre-knitty --help
    - pandoc-filter-arg --help

about:
  home: https://github.com/kiwi0fruit/knitty
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Reproducible report generation tool via Jupyter, Pandoc and Markdown. Contains fork of the Notedown."
  doc_url: https://github.com/kiwi0fruit/knitty
  dev_url: https://github.com/kiwi0fruit/knitty

extra:
  recipe-maintainers:
    - kiwi0fruit
